/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

import com.fazecast.jSerialComm.SerialPort;
import java.io.IOException;

/**
 *
 * @author alex_
 */
public class NewJFrame extends javax.swing.JFrame {
    private final SerialPort sp = SerialPort.getCommPort("COM10");
    /**
     * Creates new form NewJFrame
     */
    private void SERIAL_COM_SETUP(){
        sp.setComPortParameters(9600, 8, 1, 0);
        sp.setComPortTimeouts(SerialPort.TIMEOUT_READ_SEMI_BLOCKING, 0, 0);
        if (!sp.openPort()) {
            System.out.println("ERROR: This COM port not available.");
            System.exit(1);
        }else {
            System.out.println("COM4 opened successfully.");
        }
    }
    public NewJFrame() {
        initComponents();
        SERIAL_COM_SETUP();
    }

    private void sendByteData(byte data){
        try {
            sp.getOutputStream().write(data);
            System.out.println("Sent: " + data);
            sp.getOutputStream().flush();
        } catch(IOException e){
          System.out.println("ERROR: This COM port not available.");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        L3Sound = new javax.swing.JToggleButton();
        L1Sound = new javax.swing.JToggleButton();
        L2Sound = new javax.swing.JToggleButton();
        lightTwoButton = new javax.swing.JToggleButton();
        lightOneButton = new javax.swing.JToggleButton();
        lightThreeButton = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("sansserif", 0, 24)); // NOI18N
        jLabel1.setText("Smart Home System");
        jLabel1.setAlignmentY(0.0F);

        L3Sound.setText("L3 Sound");
        L3Sound.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                L3SoundActionPerformed(evt);
            }
        });

        L1Sound.setText("L1 Sound");
        L1Sound.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                L1SoundActionPerformed(evt);
            }
        });

        L2Sound.setText("L2 Sound");
        L2Sound.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                L2SoundActionPerformed(evt);
            }
        });

        lightTwoButton.setText("Light Two");
        lightTwoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lightTwoButtonActionPerformed(evt);
            }
        });

        lightOneButton.setText("Light one");
        lightOneButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lightOneButtonActionPerformed(evt);
            }
        });

        lightThreeButton.setText("Light Three");
        lightThreeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lightThreeButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(278, 278, 278)
                        .addComponent(jLabel1))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(97, 97, 97)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lightThreeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lightOneButton, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lightTwoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(85, 85, 85)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(L2Sound, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(L1Sound, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(L3Sound, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(73, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(L1Sound, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lightOneButton, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(55, 55, 55)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(L2Sound, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lightTwoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(56, 56, 56)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(L3Sound, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lightThreeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(105, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void L3SoundActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_L3SoundActionPerformed
        // TODO add your handling code here:
        sendByteData((byte)6);
    }//GEN-LAST:event_L3SoundActionPerformed

    private void L1SoundActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_L1SoundActionPerformed
        // TODO add your handling code here:
        sendByteData((byte)5);
    }//GEN-LAST:event_L1SoundActionPerformed

    private void L2SoundActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_L2SoundActionPerformed
        // TODO add your handling code here:
        sendByteData((byte)4);
    }//GEN-LAST:event_L2SoundActionPerformed

    private void lightTwoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lightTwoButtonActionPerformed
        // TODO add your handling code here:
        sendByteData((byte)2);
        System.out.println("Button pressed");
    }//GEN-LAST:event_lightTwoButtonActionPerformed

    private void lightOneButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lightOneButtonActionPerformed
        // TODO add your handling code here:
        sendByteData((byte)1);
        System.out.println("Button pressed");

    }//GEN-LAST:event_lightOneButtonActionPerformed

    private void lightThreeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lightThreeButtonActionPerformed
        // TODO add your handling code here:
        sendByteData((byte)3);
        System.out.println("Button pressed");

    }//GEN-LAST:event_lightThreeButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton L1Sound;
    private javax.swing.JToggleButton L2Sound;
    private javax.swing.JToggleButton L3Sound;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JToggleButton lightOneButton;
    private javax.swing.JToggleButton lightThreeButton;
    private javax.swing.JToggleButton lightTwoButton;
    // End of variables declaration//GEN-END:variables
}
